name: RakBank_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
 OC_TOKEN: ${{secrets.OC_TOKEN}}
 OC_SERVER: ${{secrets.OC_SERVER}}
 oc_USERNAME: ${{secrets.oc_USERNAME}}
 oc_PASSWORD: ${{secrets.oc_PASSWORD}}
 oc_login: ${{secrets.oc_login}}
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
      - name: oc login & deployment 
        run: |
             cd /usr/local/bin/ 
             ./oc login $OC_SERVER -u $oc_USERNAME -p $oc_PASSWORD
             ./oc project cp4i
			 
      -	name: deploying in ACE 
	    deploy-dev:
        environment: 'dev'
        needs: build-and-publish
        steps:
	    ./oc apply -f  /home/bandaru/Videos/manoj/devops-dev.yaml

       deploy-prod:
       environment: 'prod'
       needs: [build-and-publish, deploy-dev]
       steps:		 
        ./oc apply -f  /home/bandaru/Videos/manoj/devops-uat.yaml
	   
      deploy-prod:
      environment: 'prod'
      needs: [build-and-publish, deploy-uat]
      steps:		 	   
       ./oc apply -f  /home/bandaru/Videos/manoj/devops-prod.yaml 
